#!/usr/bin/env bun

/**
 * `@base/config`'s own CLI — `bun x base --output=<path> [--config=<path>]`,
 * matching `auth:gen`'s own `bun x auth@rc generate --config=... --output=...`
 * invocation shape. Generating a consumer's copy of the content schema is a
 * *library* concern — this used to be a hand-written script living in
 * `www/scripts/generate-content-schema.ts`, reaching into this package's own
 * source path directly. Moved here so no consumer app needs its own copy of
 * that logic at all, matching the "the library builds it, the consumer only
 * calls it" rule this package follows everywhere else (`createContentApiClient`,
 * `createBaseConfigRoute`).
 *
 * `--config` is accepted (not required) purely for invocation-shape parity
 * with `auth:gen` — it's reserved for future per-consumer, collection-aware
 * schema generation. Right now the schema is fixed (`documents`/`globals`,
 * see `content-schema.ts`), so there's nothing in a consumer's own config to
 * read yet; passing `--config` today is a no-op, not a silent failure.
 *
 * The generated file's own comments are stripped — the library source
 * (`content-schema.ts`) keeps its full doc comments for anyone reading it
 * directly; the consumer's generated copy is plain, comment-free code,
 * matching how `drizzle-kit generate`'s own migration output looks.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

function parseArgs(argv: string[]): Record<string, string> {
	const args: Record<string, string> = {}
	for (const arg of argv) {
		const match = /^--([^=]+)=(.*)$/.exec(arg)
		if (match) args[match[1]] = match[2]
	}
	return args
}

/**
 * Strips `//` and `/* *​/` comments while leaving string/template literal
 * *contents* untouched — a plain regex can't do this safely (it can't tell
 * a `//`/`/*` sitting inside a string apart from a real comment; this file's
 * own `sql\`...'subsecond'...\`` template has single quotes nested inside a
 * backtick string, which a naive strip would mishandle). Doesn't handle
 * `${...}` template-literal interpolation containing its own nested
 * strings/comments — not needed for this specific generated schema file,
 * which has none.
 */
function stripComments(code: string): string {
	let result = ''
	let i = 0
	while (i < code.length) {
		const two = code.slice(i, i + 2)
		if (two === '//') {
			while (i < code.length && code[i] !== '\n') i++
			continue
		}
		if (two === '/*') {
			i += 2
			while (i < code.length && code.slice(i, i + 2) !== '*/') i++
			i += 2
			continue
		}
		const char = code[i]
		if (char === '"' || char === "'" || char === '`') {
			const quote = char
			result += char
			i++
			while (i < code.length && code[i] !== quote) {
				if (code[i] === '\\') {
					result += code[i] + (code[i + 1] ?? '')
					i += 2
					continue
				}
				result += code[i]
				i++
			}
			result += code[i] ?? ''
			i++
			continue
		}
		result += char
		i++
	}
	return result
		.split('\n')
		.map((line) => line.trimEnd())
		.join('\n')
		.replace(/\n{3,}/g, '\n\n')
}

const args = parseArgs(process.argv.slice(2))

if (!args.output) {
	console.error('Usage: bun x base --output=<path> [--config=<path>]')
	process.exit(1)
}

const sourcePath = path.resolve(import.meta.dir, 'db/content-schema.ts')
const outPath = path.resolve(process.cwd(), args.output)

const header = '// AUTO-GENERATED by `bun x base` — do not hand-edit.\n\n'

const source = readFileSync(sourcePath, 'utf-8')
const generated = `${header}${stripComments(source).trimStart()}`

mkdirSync(path.dirname(outPath), { recursive: true })
writeFileSync(outPath, generated)

console.log(`Generated ${path.relative(process.cwd(), outPath)}`)
