// AUTO-GENERATED by `bun x base`: do not hand-edit.

import type { BasiccnContent } from '@baseconfig/ui/basiccn'

export interface Posts {
	body?: BasiccnContent
}

export interface Keywords {
	keywords?: {
		label?: string
	}[]
}

declare module '@baseconfig/core' {
	interface GeneratedCollectionTypes {
		posts: Posts
	}
	interface GeneratedGlobalTypes {
		keywords: Keywords
	}
}
