// AUTO-GENERATED by `bun x base`: do not hand-edit.

import type { MetaValue, NavMenuValue, UploadValue } from '@baseconfig/core'
import type { BasiccnContent } from '@baseconfig/ui/basiccn'

export interface Pages {
	hero?: {
		image?: UploadValue
		content?: BasiccnContent
		links?: {
			label?: string
			href?: string
		}[]
	}
	content?: unknown[]
	metadata?: MetaValue
}

export interface Docs {
	body?: BasiccnContent
}

export interface Topbar {
	items?: NavMenuValue
}

export interface Keywords {
	keywords?: {
		label?: string
	}[]
}

declare module '@baseconfig/core' {
	interface GeneratedCollectionTypes {
		pages: Pages
		docs: Docs
	}
	interface GeneratedGlobalTypes {
		topbar: Topbar
		keywords: Keywords
	}
}
