// AUTO-GENERATED by `bun x base`: do not hand-edit.

import type { LinkItemValue, MetaValue, NavMenuValue, UploadValue } from '@baseconfig/core'
import type { BasiccnContent } from '@baseconfig/ui/basiccn'

export interface Pages {
	hero?: {
		image?: UploadValue
		content?: BasiccnContent
		links?: {
			label?: string
			href?: string
		}[]
	}
	content?: ContentBlock[]
	metadata?: MetaValue
}

export interface Docs {
	body?: BasiccnContent
	category?: string[]
	parent?: string
	order?: number
	slug?: string
}

export interface Topbar {
	items?: NavMenuValue
}

export interface Keywords {
	keywords?: {
		label?: string
	}[]
}

export interface Category {
	category?: {
		label?: string
	}[]
}

export interface RichTextBlock {
		blockType: 'richtext'
		blockName?: string
		content?: BasiccnContent
}

export interface MediaBlock {
		blockType: 'media'
		blockName?: string
		image?: UploadValue
}

export interface CtaBlock {
		blockType: 'cta'
		blockName?: string
		content?: BasiccnContent
		links?: LinkItemValue[]
}

export interface BannerBlock {
		blockType: 'banner'
		blockName?: string
		content?: BasiccnContent
		image?: UploadValue
		links?: LinkItemValue[]
}

export interface GridBlock {
		blockType: 'grid'
		blockName?: string
		variant?: string
		items?: ContentBlock[]
}

export interface CodeBlock {
		blockType: 'code'
		blockName?: string
		language?: string
		code?: string
}

export interface RelatedPostsBlock {
		blockType: 'relatedPosts'
		blockName?: string
		label?: string
		mode?: string
		ids?: string[]
		keywords?: string[]
}

export type ContentBlock =
	| RichTextBlock
	| MediaBlock
	| CtaBlock
	| BannerBlock
	| GridBlock
	| CodeBlock
	| RelatedPostsBlock

declare module '@baseconfig/core' {
	interface GeneratedCollectionTypes {
		pages: Pages
		docs: Docs
	}
	interface GeneratedGlobalTypes {
		topbar: Topbar
		keywords: Keywords
		category: Category
	}
	interface GeneratedBlockTypes {
		richtext: RichTextBlock
		media: MediaBlock
		cta: CtaBlock
		banner: BannerBlock
		grid: GridBlock
		code: CodeBlock
		relatedPosts: RelatedPostsBlock
	}
}
