// AUTO-GENERATED by `bun x base`: do not hand-edit.

import { defineRelationsPart, sql } from 'drizzle-orm'

import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

export const pages = sqliteTable(
	'cn-pages',
	{
		id: text('id').primaryKey(),
		title: text('title'),
		slug: text('slug'),
		status: text('status', { enum: ['draft', 'published'] }).notNull().default('draft'),
		data: text('data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}),
		createdAt: integer('createdAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
		updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).$onUpdate(() => /* @__PURE__ */ new Date()).notNull()
	},
	(table) => [uniqueIndex('idx_pages_slug').on(table.slug)]
)

export const docs = sqliteTable(
	'cn-docs',
	{
		id: text('id').primaryKey(),
		title: text('title'),
		slug: text('slug'),
		status: text('status', { enum: ['draft', 'published'] }).notNull().default('draft'),
		data: text('data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}),
		createdAt: integer('createdAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
		updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).$onUpdate(() => /* @__PURE__ */ new Date()).notNull()
	},
	(table) => [uniqueIndex('idx_docs_slug').on(table.slug)]
)

export const topbar = sqliteTable('cn-topbar', {
	data: text('data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}),
	updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).$onUpdate(() => /* @__PURE__ */ new Date()).notNull()
})

export const keywords = sqliteTable('cn-keywords', {
	data: text('data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}),
	updatedAt: integer('updatedAt', { mode: 'timestamp_ms' }).default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).$onUpdate(() => /* @__PURE__ */ new Date()).notNull()
})

export const collectionTablesBySlug = {
	'pages': pages,
	'docs': docs
}

export const globalTablesBySlug = {
	'topbar': topbar,
	'keywords': keywords
}

export const contentRelations = defineRelationsPart({ pages, docs, topbar, keywords }, () => ({}))