// AUTO-GENERATED by `bun x base`: do not hand-edit.

import type { MetaValue } from '@baseconfig/core'
import type { BasiccnContent } from '@baseconfig/ui/basiccn'

export interface Products {
	product?: {
		quantity?: number
		price?: number
		stock?: number
		description?: BasiccnContent
	}
	metadata?: MetaValue
}

export interface Posts {
	body?: BasiccnContent
}

export interface Keywords {
	keywords?: {
		label?: string
	}[]
}

declare module '@baseconfig/core' {
	interface GeneratedCollectionTypes {
		products: Products
		posts: Posts
	}
	interface GeneratedGlobalTypes {
		keywords: Keywords
	}
}
